// AUTO-GENERATED by ts-rs via `pnpm bindings` — do not edit by hand.
// Run `pnpm bindings` to regenerate after changing Rust types annotated with #[derive(TS)].

// ---------------------------------------------------------------------------
// projects/mod.rs
// ---------------------------------------------------------------------------

export type Project = {
  id: string;
  name: string;
  path: string;
  tags: Array<string>;
  language: string | null;
  package_manager: string | null;
  added_at: string;
  last_modified: string | null;
  is_missing: boolean;
};

// ---------------------------------------------------------------------------
// sequences/mod.rs
// ---------------------------------------------------------------------------

export type Sequence = {
  name: string;
  description: string;
  path: string;
  mtime: string;
};

// ---------------------------------------------------------------------------
// runs/mod.rs
// ---------------------------------------------------------------------------

export type RunStatus = "Pending" | "Running" | "Completed" | "Failed" | "Stopped";

export type Run = {
  id: string;
  project_id: string;
  project_path: string;
  sequence_name: string;
  attached_md_path: string | null;
  started_at: string;
  ended_at: string | null;
  status: RunStatus;
  exit_code: number | null;
  pid: number | null;
  note: string | null;
};

export type RunEvent =
  | { type: "assistant_text"; text: string; ts: string }
  | { type: "thinking"; text: string; ts: string }
  | { type: "tool_call"; id: string; name: string; input: unknown; ts: string }
  | { type: "tool_result"; call_id: string; output: unknown; is_error: boolean; ts: string }
  | {
      type: "file_edit";
      path: string;
      diff: string;
      additions: number;
      deletions: number;
      ts: string;
    }
  | { type: "user_input"; text: string; ts: string }
  | { type: "system"; text: string; ts: string }
  | { type: "step_failed"; step: string; message: string; ts: string }
  | { type: "error"; message: string; ts: string };

export type LaunchInput = {
  project_id: string;
  sequence_name: string;
  attached_md_path: string | null;
};

export type StepFailureChoice = "Retry" | "Skip" | "Abort" | "Continue";

// ---------------------------------------------------------------------------
// settings/mod.rs
// ---------------------------------------------------------------------------

export type ViewMode = "Grid" | "List";

export type Settings = {
  parent_dir: string | null;
  claude_cli_path: string | null;
  git_poll_interval_secs: number;
  usage_poll_interval_secs: number;
  retention_days: number;
  retention_size_mb: number;
  view_mode: ViewMode;
};

export type SettingsPatch = {
  parent_dir: string | null;
  claude_cli_path: string | null;
  git_poll_interval_secs: number | null;
  usage_poll_interval_secs: number | null;
  retention_days: number | null;
  retention_size_mb: number | null;
  view_mode: ViewMode | null;
};

// ---------------------------------------------------------------------------
// usage/mod.rs
// ---------------------------------------------------------------------------

export type UsageSnapshot = {
  fetched_at: string;
  parsed: Record<string, string>;
  raw_stdout: string;
  available: boolean;
};

// ---------------------------------------------------------------------------
// projects/git.rs
// ---------------------------------------------------------------------------

export type GitStatus = {
  branch: string | null;
  is_clean: boolean;
  dirty_files: number;
  ahead: number;
  behind: number;
  last_polled: string;
  error: string | null;
};

// ---------------------------------------------------------------------------
// ipc/commands.rs
// ---------------------------------------------------------------------------

export type CliCheck = {
  found: boolean;
  resolved_path: string | null;
  version: string | null;
  error: string | null;
};
