/**
 * T0.3 — bindings.ts shape verification
 *
 * The `import type` block and `_id<T>` calls are compile-time checks: a
 * TypeScript error here means bindings.ts is missing or has the wrong shape.
 * The runtime `describe` block guards against the file being accidentally
 * replaced with the empty stub.
 */

import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

import type {
  CliCheck,
  GitStatus,
  LaunchInput,
  Project,
  Run,
  RunEvent,
  RunStatus,
  Sequence,
  Settings,
  SettingsPatch,
  StepFailureChoice,
  UsageSnapshot,
  ViewMode,
} from "./bindings";

// Compile-time shape checks: TypeScript validates each object literal against T.
function _id<T>(_x: T): void {}

describe("bindings.ts compile-time shapes", () => {
  it("Project fields are assignable", () => {
    _id<Project>({
      id: "",
      name: "",
      path: "",
      tags: [],
      language: null,
      package_manager: null,
      added_at: "",
      last_modified: null,
      is_missing: false,
    });
  });

  it("Sequence fields are assignable", () => {
    _id<Sequence>({ name: "", description: "", path: "", mtime: "" });
  });

  it("RunStatus accepts valid variant", () => {
    _id<RunStatus>("Completed");
  });

  it("Run fields are assignable", () => {
    _id<Run>({
      id: "",
      project_id: "",
      project_path: "",
      sequence_name: "",
      attached_md_path: null,
      started_at: "",
      ended_at: null,
      status: "Pending",
      exit_code: null,
      pid: null,
      note: null,
    });
  });

  it("RunEvent discriminated union covers all variants", () => {
    _id<RunEvent>({ type: "assistant_text", text: "", ts: "" });
    _id<RunEvent>({ type: "thinking", text: "", ts: "" });
    _id<RunEvent>({ type: "tool_call", id: "", name: "", input: null, ts: "" });
    _id<RunEvent>({
      type: "tool_result",
      call_id: "",
      output: null,
      is_error: false,
      ts: "",
    });
    _id<RunEvent>({
      type: "file_edit",
      path: "",
      diff: "",
      additions: 0,
      deletions: 0,
      ts: "",
    });
    _id<RunEvent>({ type: "user_input", text: "", ts: "" });
    _id<RunEvent>({ type: "system", text: "", ts: "" });
    _id<RunEvent>({ type: "step_failed", step: "", message: "", ts: "" });
    _id<RunEvent>({ type: "error", message: "", ts: "" });
  });

  it("LaunchInput fields are assignable", () => {
    _id<LaunchInput>({ project_id: "", sequence_name: "", attached_md_path: null });
  });

  it("StepFailureChoice accepts valid variant", () => {
    _id<StepFailureChoice>("Retry");
  });

  it("ViewMode accepts valid variant", () => {
    _id<ViewMode>("Grid");
  });

  it("Settings fields are assignable", () => {
    _id<Settings>({
      parent_dir: null,
      claude_cli_path: null,
      git_poll_interval_secs: 10,
      usage_poll_interval_secs: 60,
      retention_days: 30,
      retention_size_mb: 500,
      view_mode: "Grid",
    });
  });

  it("SettingsPatch fields are assignable", () => {
    _id<SettingsPatch>({
      parent_dir: null,
      claude_cli_path: null,
      git_poll_interval_secs: null,
      usage_poll_interval_secs: null,
      retention_days: null,
      retention_size_mb: null,
      view_mode: null,
    });
  });

  it("UsageSnapshot fields are assignable", () => {
    _id<UsageSnapshot>({ fetched_at: "", parsed: {}, raw_stdout: "", available: true });
  });

  it("GitStatus fields are assignable", () => {
    _id<GitStatus>({
      branch: null,
      is_clean: true,
      dirty_files: 0,
      ahead: 0,
      behind: 0,
      last_polled: "",
      error: null,
    });
  });

  it("CliCheck fields are assignable", () => {
    _id<CliCheck>({ found: false, resolved_path: null, version: null, error: null });
  });
});

describe("bindings.ts file integrity", () => {
  const BINDINGS_PATH = join(import.meta.dirname, "bindings.ts");

  it("is readable and non-empty (not the empty stub)", () => {
    const content = readFileSync(BINDINGS_PATH, "utf-8");
    expect(content.length).toBeGreaterThan(0);
    expect(content.trim()).not.toBe("export {};");
  });

  it("contains the AUTO-GENERATED header", () => {
    const content = readFileSync(BINDINGS_PATH, "utf-8");
    expect(content).toContain("AUTO-GENERATED by ts-rs");
  });
});
